services: 
  mySQLcontained: 
    image: mysql
    environment:
     - MYSQL_ROOT_PASSWORD=mysqlpwd
    ports: 
     - 3306:3306

  websvr_contained: 
    build: ./LAMPcontained
    volumes: 
     - ./LAMPcontained/data:/var/www/html
    ports: 
     - 80:80
    links: 
     - mySQLcontained
    depends_on:
     - mySQLcontained
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: PMAcontained
    environment: 
     - PMA_HOST=mySQLcontained
     - MYSQL_ROOT_PASSWORD=mysqlpwd
     - PMA_PORT=3306
    ports: 
     - 8080:80